# Basado en flutter_lints, con reglas adicionales útiles para apps productivas.
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    always_declare_return_types: warning
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    unnecessary_const: warning
    public_member_api_docs: ignore # súbelo a warning si documentamos API pública
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - avoid_function_literals_in_foreach_calls
    - avoid_print
    - avoid_redundant_argument_values
    - cascade_invocations
    - curly_braces_in_flow_control_structures
    - diagnostic_describe_all_properties
    - directives_ordering
    - join_return_with_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_await_in_return
    - use_decorated_box # en vez de Container sin decoración
    - use_key_in_widget_constructors
    - use_super_parameters

# Config opcional para dart_code_metrics (si lo añadimos más abajo)
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 120
    maximum-nesting-level: 4
    number-of-parameters: 6
    source-lines-of-code: 100
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-magic-number:
        severity: style
        allowed: [0, 1, 2, 10, 60, 1000]
    - prefer-trailing-comma
    - no-empty-block
